export interface LocalFile {
    name: string;
    date: string;
    data: string;
  }
export interface stc_ec_culte {
    value: string, 
    intitule: string
}
export interface declaration_culte {
    value: string
}
export interface controle_culte {
    value: string, 
    description: string
}
export interface Code_pr_temp {
    code_pr: string, 
    code_pr_temp: string, 
    id_proj: string, 
    id_activ: number, 
    id_benef: string, 
    id_bloc: string, 
    code_achat: string, 
    id_collaborateur: string, 
    id_tech: number, 
    etat: string, 
    status: string
}
export interface Generate_code_pms {
    code_benef_pms: string,
    code_pms_temp: string,
    code_achat: string,
    id_proj: string,
    id_benef: string,
    id_activ: number,
    id_association: string,
    status: string,
    etat: string
}
export interface Loc_all_contrat_pms {
    code: string, 
    code_contrat: string, 
    id_annee: number, 
    id_saison: string, 
    id_pms: string,
    code_ass: string,
    code_benef_pms: string, 
    nom: string, 
    prenom: string,
    id_parce: string, 
    ref_gps: string, 
    lat: number, 
    log: number, 
    id_var: string,
    variette: string,
    objectif: number, 
    etat: string, 
    commentaire: string
}
export interface Update_FormModal_Suivi_Mep_Bloc {
    ddp: string,
    stc: any,
    ec: any,
    ql: number,
    qr: number,
    hauteur: number,
    long_ligne: number,
    nbre_ligne: number,
    nbre_pied: number,
    estimation: number,
    unite_estimation: string,
    img_culture: string
  }
export interface Update_infos_benef {
    association: Loc_association,
    bloc: Loc_Bloc,
    collaborateur: Loc_Collabo_Activite,
    img_pr: LocalFile,
    nom: string,
    prenom: string,
    surnom: string,
    sexe: string,
    dt_naissance: string,
    dt_naissance_vers: string,
    cin: number,
    img_cin_1: LocalFile,
    img_cin_2: LocalFile,
    dt_delivrance: string,
    lieu_delivrance: string,
    code_achat: string,
    contact: string,
    region: Loc_region,
    district: Loc_district,
    commune: Loc_Commune,
    fokontany: Loc_Fokontany,
    village: string
  }
export interface Loc_export_excel {
    data: any[],
    name_feuille: string,
    name_file: string
}
export interface sc_culture {
    value: string, 
    description: string
}
export interface Update_Form_ParceSaison {
    annee: Loc_AnneeAgricole,
    saison: Loc_saison,
    parcelle: Loc_Parce_saison, //
    isNewparce: boolean,
    espece: Loc_Espece,
    variette: Loc_variette,
    objectif: number,
    ref_gps_saison: string,
    latitude_saison: number,
    longitude_saison: number,
    ref_gps: string,
    latitude: number,
    longitude: number,
    superficie: number,
    region: Loc_region,
    district: Loc_district,
    commune: Loc_Commune,
    fokontany: Loc_Fokontany,
    village: string
}
export interface Loc_projet {
    numero: number, 
    code_proj: string, 
    nom: string, 
    description: string, 
    ancronyme: string,
    logo: string, 
    statuts: string
}
export interface Loc_collaborateur {
    code_col: string, 
    nom: string, 
    description: string, 
    ancronyme: string
}
export interface Loc_Collabo_Activite {
    code: number, 
    id_col: string, 
    nom: string, 
    description: string, 
    ancronyme: string, 
    id_activ: number
}
export interface Loc_activ_projet {
    code: number, 
    id_proj: string, 
    nom: string,
    id_equipe: number, 
    id_volet: number, 
    id_activ: number, 
    intitule: string, 
    description: string, 
    statuts: string
}
export interface Loc_association {
    numero: number,
    id_prjt: string,
    code_proj: string, 
    nom_pr: string, 
    id_fkt:  string, 
    nom_fkt: string,
    code_ass: string, 
    nom_ass: string,
    ancronyme: string,
    id_tech: number, 
    technicien: string,
    nb_benef: number, 
    nom_pa: string,
    prenom: string,
    sexe: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_benef: Blob,
    surnom: string,
    status: string
}
export interface Generate_code_contrat_pms {
    code: string,
    code_contrat: string,
    id_annee: number,
    id_saison: string,
    id_pms: string,
    id_parce: string,
    ref_gps: string,
    lat: number,
    log: number,
    id_var: string,
    objectif: string,
    etat: string,
    commentaire: string
}
export interface Local_Parcelle {
    id_annee: number, 
    id_saison: string,
    code_contrat: string,
    id_pms: string,
    fkt_association: string,
    id_association: string,
    nom_ass: string,
    code_benef_pms: string,
    code_achat: string,
    nom: string,
    prenom: string,
    code_parce: string,
    code_parce_temp: string,
    id_benef: string,
    ref_gps: string,
    lat: string,
    log: string,
    superficie: string,
    id_fkt: string,
    status: string
}
export interface Loc_Parce_saison {
    code_parce_saison: string,
    code_contrat: string,
    id_annee: number,
    annee_du: number, 
    annee_au: number, 
    id_saison: string,
    saison: string,
    id_pms: string,
    code_pms_temp: string,
    code_achat: string, 
    nom: string, 
    prenom: string, 
    dt_nais: string, 
    dt_nais_vers: string,
    date_naissance: string,
    sexe: string, 
    cin: number,
    id_parce: string,
    ref_gps_saison: string, 
    lat_saison: number, 
    log_saison: number,
    id_var: string,
    code_espece: string,
    variette: string,
    objectif: number,
    unite_objectif: string,
    etat_contrat: string,
    commentaire: string,  
    code_ass: string, 
    association: string,        
    code_parce: string,
    code_parce_temp: string,
    ref_gps_parce: string,
    lat_parce: number,
    log_parce: number,
    id_assoc_prc: string, 
    id_benef_prc: string, 
    ref_gps: string, 
    latitude: number, 
    logitude: number, 
    superficie: number, 
    id_fkt: string, 
    fokontany_prc: string,
    code_reg: string,
    code_dist: string,
    nom_dist: string,
    code_commune: string,
    nom_commune: string,
    village: string,
    etat_parce: string,
    status_prc: string,
    indication: string
}
export interface Find_contrat_pms {
    code_contrat: string,
    code_contrat_temp: string,
    id_annee: string,
    id_saison: string,
    id_pms: string,
    id_parce: string,
    ref_gps: string,
    lat: string,
    log: string,
    id_var: string,
    objectif: string,
    etat: string,
    commentaire: string
}
export interface Find_mep_contrat_pms {
    code_culture: string,
    id_contrat: string,
    id_parce: string,
    id_var: string,
    id_saison: string,
    id_annee: string,
    ddp: string,
    qsa: number,
    img_fact: string,
    dds: string,
    sfce: number,
    sc: string,
    ea_id_variette: string, 
    ea_autres: string,
    dt_creation: string,
    dt_modification: string,
    statuts: string,
    Etat: string
}
export interface Find_suivi_MEP_pms {
    code_suivi: string,
    id_culture: string,
    ddp: string,
    stc: string,
    ec: string,
    pb: string,
    ex: number,
    img_cult: string,
    name: string,
    controle: string,
    declaration: string, 
    etat: string
}
export interface Generate_code_assoc_parce {
    code_parce: string, 
    code_parce_temp: string, 
    id_assoc: string, 
    id_benef: string, 
    ref_gps: string, 
    lat: number, 
    log: number, 
    superficie: string, 
    id_fkt: string, 
    id_commune: string, 
    village: string, 
    anne_adheran: string, 
    indication: string, 
    etat: string, 
    status: string
}
export interface Benef_activ_pms {
    id_annee: number, 
    id_saison: string, 
    id_pms: string,
    id_activ: number,
    intitule: string,
    id_proj: string,
    nom_pr: string,
    fkt_association: string,
    id_association: string,
    nom_ass: string,
    code_benef_pms: string,
    code_pms_temp: string,
    code_achat: string,
    id_benef: string,
    code_benef: string,
    img_benef: string,
    nom_benef: string,
    prenom: string,
    sexe: string,
    dt_nais: string,
    dt_nais_vers: string,
    data_naissance: string,
    surnom: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_cin: string,
    contact: string,
    code_region: string,
    code_district: string,
    nom_district: string,
    code_commune: string,
    nom_commune: string,
    id_fkt: string,
    village: string,
    adress: string,
    id_collaborateur: string,
    nom_collab: string,
    etat_benef: string,
    etat_pms: string,
    statut: string,
    parcelle: Loc_Parce_saison[],
    isExpanded: boolean,
}

export interface Loc_Bloc {
    ordre: number,
    code_bloc: string,
    nom_bloc: string,
    ancronyme: string,
    nb_benef: number,
    nb_parce: number,
    id_district: string,
    id_prjt: string,
    id_tech: string,
    status : string,
    nom: string,
    prenom: string,
    sexe: string,
    cin: string,
    nom_dist: string,
    zone: Local_bloc_zone[],
    isExpanded: boolean
}
export interface Local_benef_activ_bl {
    code_benef_bl: string, 
    code_benef_bl_temp: string,
    id_proj: string, 
    id_activ: number, 
    id_benef: string, 
    id_bloc: string, 
    nom_bloc: string,
    code_achat: string, 
    id_collaborateur: string, 
    etat_benef_bloc: string, 
    status: string, 
    code_benef: string, 
    img_benef: string, 
    nom: string, 
    prenom: string, 
    sexe: string, 
    dt_nais: string, 
    dt_nais_vers: string, 
    surnom: string, 
    cin: number, 
    dt_delivrance: string, 
    lieu_delivrance: string, 
    img_cin: string, 
    contact: string, 
    id_fkt: string, 
    id_commune: string, 
    village: string, 
    dt_insert_bnf: string, 
    etat_bnf: string, 
    status_bnf: string, 
    nb_parce: number,  
    sum_parce: number,
    date_naissance: string,
    code_reg: string,
    code_dist: string,
    nom_dist: string,
    code_commune: string,
    commune: string,
    fokontany: string,
    parcelle: Local_bloc_parce[],
    isExpanded: boolean
}
export interface Find_mep_parce_bloc {
    code_culture: string,
    id_parce: string,
    id_espece: string,
    id_var: string,
    id_saison: string,
    id_annee: string,
    ddp: string,
    qso: number,
    dt_distribution: string,
    dds: string,
    sfce: number,
    nbre_ligne: number,
    long_ligne: number,
    usage: string,
    sc: string,
    ea_autres: string,
    ea_id_variette: string,
    dt_creation: string,
    dt_modification: string,
    status: string,
    etat: string,
    id_equipe: number,
    type: string
}
export interface Find_parce_benf_bloc {
    code_parce: string,
    code_parce_temp: string,
    id_bloc: string,
    id_benef: string,
    ref_gps: string,
    lat: number,
    log: number,
    superficie: number,
    id_fkt: string,
    id_commune: string,
    village: string,
    anne_adheran: string,
    indication: string,
    etat: string,
    status: string
}
export interface Local_bloc_zone {
    code: number,
    id_bloc: string,
    nom_bloc: string,
    nom_com: string,
    id_fkt: string,
    nom_fkt: string,
    id_km: string,
    nom: string,
    prenom: string
}
export interface Local_bloc_parce {
    id_bloc: string,
    nom_bloc: string,
    code_benef_bl: string,
    nom: string,
    prenom: string,
    code_parce: string,
    code_parce_temp: string,
    ref_gps: string,
    lat: number,
    log: number,
    superficie: number,
    anne_adheran: string,
    status: string,
    id_fkt: string,
    id_commune: string, 
    village: string, 
    indication: string, 
    etat: string,
    code_reg: string,
    code_dist: string,
    district: string,
    code_commune: string,
    commune: string,
    fokontany: string
}
export interface Loc_saison {
    code_saison: string,
    intitule: string,
    description: string
}
export interface Loc_categEspece {
    code_cat: number,
    libelle: string
}
export interface Loc_Espece {
    code_espece: string,
    nom_espece: string,
    id_categ: number,
    libelle: string,
    saisonnier: number,
    unite: string,
    unite_estimation: string,
    unite_objectif: string
}
export interface Loc_variette {
    code_var: string,
    nom_var: string,
    id_espece: string,
    nom_espece: string
}
export interface Loc_culture_Pms {
    code_culture: string,
    id_contrat: string,
    code_contrat_temp: string,
    id_parce: string,
    code_parce_temp: string,
    superficie: number,
    code_benef_pms: string,
    code_pms_temp: string,
    code_achat: string,
    nom: string,
    prenom: string,
    sexe: string,
    dt_nais: string, 
    dt_nais_vers: string,
    date_naissance: string,
    cin: number,
    code_espece: string, 
    nom_espece: string,
    id_var: string,
    nom_var: string,
    unite_espece: string,
    unite_estimation: string,
    unite_objectif: string,
    id_saison: string,
    saison: string,
    code_ass: string,
    association: string,
    id_annee: number,
    annee_du: number,
    annee_au: number,
    ddp: string,
    qsa: number,
    img_fact: Blob,
    dds: string,
    sfce: number,
    sc: string,
    nb_ligne: number,
    long_ligne: number,
    ea_id_espece: string,
    ea_id_variette: string,
    ea_autres: string,
    ea: string,
    dt_creation: string,
    dt_modification: string,
    statuts: string,
    etat_mep: string,
    suivi: Loc_all_suivi_mep[],
    isExpanded: boolean
}
// interface suivi culture
export interface Loc_suivi_mep {
    id: string,
    id_culture: string,
    ddp: string,
    stc: string,
    ec: string,
    pb: string,
    ex: number,
    img_cult: string,
    name: string,
    path: string,
    controle: string,
    declaration: string
}
export interface Loc_all_suivi_mep {
    id: string,
    code_parce_temp: string,
    id_culture: string,
    code_ass: string,
    association: string,
    code_pms: string,
    code_pms_temp: string,
    code_achat: string,
    nom: string,
    prenom: string,
    sexe: string, 
    dt_nais: string, 
    dt_nais_vers: string, 
    cin: number,
    code_contrat: string,
    id_parce: string,
    superficie_reel: number,
    id_var: string,
    nom_espece: string,
    unite: string, 
    unite_estimation: string,
    nom_var: string,
    id_saison: string,
    saison: string,
    desc_saison: string,
    id_annee: number, 
    annee_du: number, 
    annee_au: number,
    qsa: number,
    dds: string,
    sfce: number,
    sc: string,
    ddp: string,
    stc: string,
    stc_intitule: string,
    ec: string,
    ec_intitule: string,
    pb: string,
    ex: number,
    img_cult: string,
    name: string,
    controle: string,
    controle_intitule: string,
    declaration: string,
    declaration_intitule: string,
    etat_suivi: string
}
export interface Loc_sv_bloc {
    code_sv: string, 
    id_culture: string, 
    ddp: string,
    sc: string, 
    ea_autre: string, 
    ea_id_var: string, 
    stc: string, 
    ql: number, 
    qr: number, 
    long_ligne: number, 
    nbre_ligne: number, 
    nbre_pied: number, 
    hauteur: number,
    ec: string,
    img_cult: string,
    dt_capture: string,
    ex: string,
    etat: string
}
export interface Loc_mep_info_bloc {
    code_bloc: string,
    nom_bl: string, 
    code_benef_bl: string,
    code_benef_bl_temp: string,
    nom: string, 
    prenom: string, 
    id_parce: string,
    code_parce_temp: string,
    id_annee: number,
    annee_du: number,
    annee_au: number, 
    sfce_reel: string,  
    lat: number, 
    log: number,
    mep: Loc_mep_bloc[],
    isExpanded: boolean 
}
export interface Loc_mep_bloc {
    code_culture: string,
    code_culture_temp: string,
    code_bloc: string,
    nom_bl: string, 
    code_benef_bl: string,
    code_benef_bl_temp: string,
    nom: string, 
    prenom: string,
    sexe: string,
    dt_nais: string,
    dt_nais_vers: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    id_parce: string,
    code_parce_temp: string,
    sfce_reel: string,
    ref_gps: string, 
    lat: number, 
    log: number,
    id_espece: string, 
    id_var: string, 
    id_saison: string,
    intitule: string, 
    id_annee: number,
    annee_du: number,
    annee_au: number,
    ddp: string, 
    qso: number, 
    dt_distribution: string,
    dds: string, 
    sfce: number, 
    nbre_ligne: number,
    long_ligne: number,
    usage: string,
    sc: string, 
    ea_autres: string, 
    ea_id_variette: string, 
    dt_creation: string, 
    dt_modification: string, 
    status: string, 
    etat_mep: string, 
    id_equipe: number, 
    type: string, 
    code_espece: string,
    nom_var: string, 
    unite_espece: string,
    unite_estimation: string,
    code_espece_ea: string,
    nom_espece: string,
    ea: string,
    suivi_Mep: Loc_all_suivi_bloc[],
    isExpanded: boolean
}
export interface Loc_all_suivi_bloc {
    code_sv: string, 
    bloc: string, 
    id_culture: string,
    code_culture_temp: string,
    id_parce: string,
    code_parce_temp: string,
    sfce_reel: number,
    code_benef_bl: string,
    code_benef_bl_temp: string,
    nom: string,
    prenom: string,
    sexe: string, 
    dt_nais: string, 
    dt_nais_vers: string, 
    cin: string,
    id_espece: string, 
    id_var: string, 
    id_saison: string,
    saison: string,
    id_annee: number, 
    annee_du: number, 
    annee_au: number,
    qso: number, 
    dds: string, 
    sfce: number,
    mep_sc: string, 
    ea_autres: string,
    ea_id_variette: string, 
    ddp: string, 
    stc: string,
    stc_intitule: string,
    ec: string,
    ec_intitule: string,
    ql: number, 
    qr: number, 
    long_ligne: number, 
    nbre_ligne: number, 
    nbre_pied: number, 
    hauteur: number,
    img_cult: string, 
    ex: string, 
    etat_suivi: string,
    espece: string,
    variette: string,
    unite_espece: string,
    unite_estimation: string,
    type: string
}
export interface Find_suivi_mep_bloc {
    code_sv: string,
    id_culture: string,
    ddp: string,
    stc: string,
    ql: number,
    qr: number,
    long_ligne: number,
    nbre_ligne: number,
    nbre_pied: number,
    hauteur: number,
    ec: string,
    img_cult: string,
    dt_capture: string,
    ex: string,
    dt_creation: string,
    dt_modification: string,
    etat: string
}
export interface Loc_PR {
    img_benef: string, 
    nom: string, 
    prenom: string, 
    sexe: string, 
    dt_nais: string, 
    dt_nais_vers: string, 
    date_naissance: string,
    surnom: string, 
    cin: number, 
    dt_delivrance: string,
    lieu_delivrance: string,
    img_cin: string, 
    contact: string, 
    id_fkt: string, 
    village: string, 
    code_region: string,
    nom_region: string,
    code_dist: string,
    nom_dist: string,
    code_commune: string,
    commune: string,
    fokontany: string,
    code_pr: string,
    code_pr_temp: string,
    id_proj: string, 
    id_activ: number, 
    id_benef: string, 
    id_bloc: string, 
    bloc: string,
    code_achat: string, 
    id_collaborateur: string, 
    id_tech: number, 
    etat_pr: string, 
    status: string,
    cep_pr: Loc_cep_PR[], // parcelle champs ecole des paysants relais
    isExpanded: boolean // si la ligne est expendable
}
export interface Loc_code_cep_PR {
    code_parce: string, 
    code_parce_temp: string, 
    id_bloc: string, 
    id_benef: string, 
    ref_gps: string, 
    lat: number, 
    log: number, 
    superficie: number, 
    id_commune: string, 
    id_fkt: string, 
    village: string, 
    anne_adheran: string, 
    dt_creation: string, 
    etat: string, 
    status: string
}
export interface Find_mep_cep {
    code_culture: string,
    id_parce: string,
    id_espece: string,
    id_var: string,
    id_saison: string,
    id_annee: number,
    ddp: string,
    qso: number,
    dt_distribution: string,
    dds: string,
    sfce: number,
    nbre_ligne: number,
    long_ligne: number,
    usage: string,
    sc: string,
    ea_autres: string,
    ea_id_variette: string,
    dt_creation: string,
    dt_modification: string,
    status: string,
    etat: string,
    id_equipe: number,
    type: string
}
export interface Loc_cep_PR {
    code_pr: string, 
    code_parce: string,
    code_parce_temp: string,
    id_bloc: string, 
    id_benef: string, 
    ref_gps: string,
    lat: number,
    log: number,
    superficie: number,
    id_commune: string,
    id_fkt: string,
    village: string,
    anne_adheran: string,
    dt_creation: string,
    etat: string,
    status: string,
    bloc_cep: string,
    code_region: string,
    nom_region: string,
    code_district: string,
    district: string,
    code_commune: string,
    commune: string,
    fokontany: string
}
export interface Loc_region {
    code_reg: string, 
    nom_reg: string
}
export interface Loc_district {
    code_dist: string, 
    nom_dist: string, 
    id_reg: string
}
export interface Loc_Commune {
    nom_reg: string,
    id_dist: string, 
    nom_dist: string,  
    code_com: string, 
    nom_com: string
}
export interface Loc_Fokontany {
    id_reg: string,
    nom_reg: string,
    id_dist: string,
    nom_dist: string,
    id_com: string,
    nom_com: string,
    code_fkt: string,
    nom_fkt: string
}
export interface Find_animationPR {
    code_anime: string,
    id_pr: string,
    id_fkt: string,
    id_commune: string,
    village: string,
    date_anim: string,
    nb_participant: number,
    nb_h: number,
    nb_f: number,
    nb_inf_25: number,
    type: string,
    img_piece: string,
    img_group_particip: string,
    id_tech_recenseur: string,
    etat: string,
    status: string
}
export interface Find_cepPR {
    code_parce: string,
    code_parce_temp: string,
    id_bloc: string,
    id_benef: string,
    ref_gps: string,
    lat: number,
    log: number,
    superficie: number,
    id_commune: string,
    id_fkt: string,
    village: string,
    anne_adheran: string,
    dt_creation: string,
    etat: string,
    status
}
export interface Loc_AnimationVe {
    code_benef: string,
    nom: string, 
    prenom: string,
    date_naissance: string,
    cin: string,
    code_pr: string,
    code_pr_temp: string,
    code_achat: string, 
    code_anime: string, 
    id_pr: string, 
    id_fkt: string, 
    village: string, 
    date_anim: string, 
    nb_participant: number, 
    nb_h: number, 
    nb_f: number, 
    nb_inf_25: number, 
    type: string, 
    img_piece: string, 
    img_group_particip: string, 
    id_tech_recenseur: number, 
    etat: string, 
    status: string,
    nb_specu: number,
    somme_specu: number,
    code_reg: string,
    code_dist: string, 
    nom_dist: string, 
    code_commune: string, 
    commune: string, 
    fokontany: string,
    specu_animation: Loc_AnimationSpecu[],
    isExpanded: boolean
}
export interface Loc_AnimationSpecu {
    code_specu: number, 
    id_anime_ve: string, 
    id_var: string, 
    id_espece: string, 
    quantite: number, 
    etat: string, 
    status: string,
    speculation: string,
    unite_espece: string
}
export interface Loc_MepPr_info {
    id_parce: string,
    code_parce_temp: string,
    lat: number,
    log: number,
    sfce: number,
    code_pr: string,
    code_pr_temp: string,
    code_achat: string, 
    img_benef: string,
    nom: string, 
    prenom: string, 
    dt_nais: string,
    cin: number,
    id_annee: number, 
    annee_du: number, 
    annee_au: number,
    mep: Loc_MepPR[],
    isExpanded: boolean
}
export interface Loc_MepPR {
    code_culture: string,
    code_culture_temp: string,
    id_parce: string,
    code_parce: string,
    code_parce_temp: string,
    lat: number,
    log: number,
    sfce_reel: number, 
    code_pr: string,
    code_pr_temp: string,
    code_achat: string, 
    img_benef: string, 
    nom: string, 
    prenom: string,
    sexe: string,
    dt_nais: string,
    dt_nais_vers: string,
    date_naissance: string,
    cin: number,
    id_espece: string, 
    id_var: string,
    variette: string,
    unite_espece: string,
    unite_estimation: string,
    code_espece_var_sg: string,
    id_saison: string,
    saison: string, 
    id_annee: number, 
    annee_du: number, 
    annee_au: number,
    ddp: string, 
    qso: number, 
    dt_distribution: string, 
    dds: string, 
    sfce_emb: number, 
    nbre_ligne: number, 
    long_ligne: number, 
    usage: string, 
    sc: string, 
    ea_autres: string, 
    code_espece_ea: string,
    ea_id_variette: string,
    cult_associe: string,
    dt_creation: string, 
    dt_modification: string, 
    status: string, 
    etat_mep: string, 
    etat_cep: string, 
    etat_benef: string, 
    etat_benef_pr: string,
    id_equipe: number, 
    type: string,
    suivi_Mep: Loc_Suivi_MepPR[],
    isExpanded: boolean
}
export interface Loc_Suivi_MepPR {
    code_pr: string, 
    nom: string, 
    prenom: string, 
    id_espece: string, 
    id_var: string, 
    variette: string,
    unite_estimation: string,
    dt_distribution: string, 
    qso: number, 
    dds: string, 
    sc: string, 
    sfce_emblavee: number, 
    code_parce: string,
    code_parce_temp: string,
    sfce_reel: number, 
    type_mep: string, 
    code_sv: string, 
    id_culture: string, 
    ddp: string, 
    stc: string,
    stc_intitule: string,
    ql: number, 
    qr: number, 
    long_ligne: number, 
    nbre_ligne: number, 
    nbre_pied: number, 
    hauteur: number, 
    ec: string, 
    ec_intitule: string,
    img_cult: string, 
    dt_capture: string, 
    ex: number, 
    dt_creation: string, 
    dt_modification: string, 
    etat_suivi: string, 
    etat_mep: string, 
    etat_cep: string, 
    etat_pr: string
}
export interface Find_suivi_MepPR {
    code_sv: string,
    id_culture: string,
    ddp: string,
    stc: string,
    ql: number,
    qr: number,
    long_ligne: number,
    nbre_ligne: number,
    nbre_pied: number,
    hauteur: number,
    ec: string,
    img_cult: string,
    dt_capture: string,
    ex: number,
    dt_creation: string,
    dt_modification: string,
    etat: string
}
export interface Loc_AnneeAgricole {
    code: number,
    annee_du: number, 
    annee_au: number, 
    statut: number
}
export interface Loc_generate_code_benef {
    code_benef_bl: string, 
    nom: string, 
    prenom: string, 
    code_benef_bl_temp: string, 
    id_proj: string, 
    id_activ: number, 
    id_benef: string, 
    id_bloc: string,
    code_achat: string, 
    id_collaborateur: string, 
    etat: string, 
    status: string
}
export interface Loc_Bloc_Parce_All {
    code_parce: string, 
    code_parce_temp: string, 
    id_bloc: string, 
    bloc: string,
    id_benef: string, 
    ref_gps: string, 
    lat: number, 
    log: number, 
    superficie: number, 
    id_fkt: string, 
    id_commune: string, 
    village: string, 
    anne_adheran: string, 
    indication: string, 
    etat: string, 
    status: string,
    code_region_parce: string,
    code_district_parce: string,
    code_commune_parce: string,
    commune_parce: string,
    fokontany_parce: string,
    code_benef_bl: string, 
    code_benef_bl_temp: string,
    img_benef: string,
    nom: string, 
    prenom: string,
    sexe: string,
    cin: number, 
    dt_nais: string, 
    dt_nais_vers: string, 
    surnom: string,
    date_naissance: string,
    commune_benef: string,
    fokontany_benef: string
}